In [ ]:
import numpy as np

In [ ]:
print("Hello Vikas")

Hello Vikas


In [ ]:
myarr= np.array([[3,5,6,7,8]] , np.int8)

In [ ]:
myarr

array([[3, 5, 6, 7, 8]], dtype=int8)

In [ ]:
myarr[0, 1]

5

In [ ]:
myarr.shape

(1, 5)

In [ ]:
myarr.dtype

dtype('int8')

In [ ]:
myarr[0, 0] = 45

In [ ]:
myarr

array([[45,  5,  6,  7,  8]], dtype=int8)

**Array Creation from other python sturctures**

In [ ]:
listarray = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [ ]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
listarray.size

9

In [ ]:
np.array({23,45,6,7,9})

array({23, 6, 7, 9, 45}, dtype=object)

In [ ]:
zero = np.zeros((3,5))

In [ ]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
rng = np.arange(10)

In [ ]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
lspace = np.linspace(1, 100, 4)

In [ ]:
lspace

array([  1.,  34.,  67., 100.])

In [ ]:
emp = np.empty((4, 6))

In [ ]:
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [ ]:
emp_like = np.empty_like(lspace)

In [ ]:
emp_like

array([  1.,  34.,  67., 100.])

In [ ]:
ide = np.identity(45)

In [ ]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
ide.shape

(45, 45)

In [ ]:
arr = np.arange(100)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
arr.reshape(2, 50)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [ ]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
arr.shape

(100,)

In [ ]:
x = [[1,2,3], [4,5,6], [7,8,9]]

In [ ]:
ar = np.array(x)

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
ar.sum(axis=0)

array([12, 15, 18])

In [ ]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [ ]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
ar.flat

In [ ]:
for item in ar.flat:
  print(item)

1
2
3
4
5
6
7
8
9


In [ ]:
ar.ndim

2

In [ ]:
ar.size

9

In [ ]:
ar.nbytes

72

In [ ]:
one = np.array([1,21,13,24,55])

In [ ]:
one.argmax()
#it gives max element's index 

4

In [ ]:
one.argmin()
#it gives min element's index 

0

In [ ]:
one.argsort() 
# it gives index of sorting order

array([0, 2, 1, 3, 4])

In [ ]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
ar.argmax(axis=1)

array([2, 2, 2])

In [ ]:
ar.argmin(axis=0)

array([0, 0, 0])

In [ ]:
ar.ravel

<function ndarray.ravel>

In [ ]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
type(np.where(ar > 5))

tuple

In [ ]:
np.where(ar > 5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [ ]:
np.count_nonzero(ar)

9

In [ ]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))